package be.imgn.mtg.engine.oracle;

import java.util.List;

/// MTG creature subtypes (Rule 205.3m).
public enum CreatureType implements Subtype {
    ADVISOR("Advisor"),
    AETHERBORN("Aetherborn"),
    ALIEN("Alien"),
    ALLY("Ally", "Allies"),
    ANGEL("Angel"),
    ANTELOPE("Antelope"),
    APE("Ape"),
    ARCHER("Archer"),
    ARCHON("Archon"),
    ARMADILLO("Armadillo"),
    ARMY("Army", "Armies"),
    ARTIFICER("Artificer"),
    ASSASSIN("Assassin"),
    ASSEMBLY_WORKER("Assembly-Worker"),
    ASTARTES("Astartes", "Astartes"),
    ATOG("Atog"),
    AUROCHS("Aurochs", "Aurochs"),
    AVATAR("Avatar"),
    AZRA("Azra"),
    BADGER("Badger"),
    BALLOON("Balloon"),
    BARBARIAN("Barbarian"),
    BARD("Bard"),
    BASILISK("Basilisk"),
    BAT("Bat"),
    BEAR("Bear"),
    BEAST("Beast"),
    BEAVER("Beaver"),
    BEEBLE("Beeble"),
    BEHOLDER("Beholder"),
    BERSERKER("Berserker"),
    BIRD("Bird"),
    BISON("Bison"),
    BLINKMOTH("Blinkmoth"),
    BOAR("Boar"),
    BRINGER("Bringer"),
    BRUSHWAGG("Brushwagg"),
    CAMARID("Camarid"),
    CAMEL("Camel"),
    CAPYBARA("Capybara"),
    CARIBOU("Caribou"),
    CARRIER("Carrier"),
    CAT("Cat"),
    CENTAUR("Centaur"),
    CHILD("Child", "Children"),
    CHIMERA("Chimera"),
    CITIZEN("Citizen"),
    CLERIC("Cleric"),
    CLOWN("Clown"),
    COCKATRICE("Cockatrice"),
    CONSTRUCT("Construct"),
    COWARD("Coward"),
    COYOTE("Coyote"),
    CRAB("Crab"),
    CROCODILE("Crocodile"),
    CTAN("C'tan", "C'tan"),
    CUSTODES("Custodes", "Custodes"),
    CYBERMAN("Cyberman"),
    CYCLOPS("Cyclops", "Cyclops"),
    DALEK("Dalek"),
    DAUTHI("Dauthi", "Dauthi"),
    DEMIGOD("Demigod"),
    DEMON("Demon"),
    DESERTER("Deserter"),
    DETECTIVE("Detective"),
    DEVIL("Devil"),
    DINOSAUR("Dinosaur"),
    DJINN("Djinn", "Djinn"),
    DOCTOR("Doctor"),
    DOG("Dog"),
    DRAGON("Dragon"),
    DRAKE("Drake"),
    DREADNOUGHT("Dreadnought"),
    DRIX("Drix", "Drix"),
    DRONE("Drone"),
    DRUID("Druid"),
    DRYAD("Dryad"),
    DWARF("Dwarf", "Dwarves"),
    ECHIDNA("Echidna"),
    EFREET("Efreet"),
    EGG("Egg"),
    ELDER("Elder"),
    ELDRAZI("Eldrazi", "Eldrazi"),
    ELEMENTAL("Elemental"),
    ELEPHANT("Elephant"),
    ELF("Elf", "Elves"),
    ELK("Elk"),
    EMPLOYEE("Employee"),
    EYE("Eye"),
    FAERIE("Faerie"),
    FERRET("Ferret"),
    FISH("Fish", "Fish"),
    FLAGBEARER("Flagbearer"),
    FOX("Fox", "Foxes"),
    FRACTAL("Fractal"),
    FROG("Frog"),
    FUNGUS("Fungus", "Funguses"),
    GAMER("Gamer"),
    GARGOYLE("Gargoyle"),
    GERM("Germ"),
    GIANT("Giant"),
    GITH("Gith", "Gith"),
    GLIMMER("Glimmer"),
    GNOLL("Gnoll"),
    GNOME("Gnome"),
    GOAT("Goat"),
    GOBLIN("Goblin"),
    GOD("God"),
    GOLEM("Golem"),
    GORGON("Gorgon"),
    GRAVEBORN("Graveborn", "Graveborn"),
    GREMLIN("Gremlin"),
    GRIFFIN("Griffin"),
    GUEST("Guest"),
    HAG("Hag"),
    HALFLING("Halfling"),
    HAMSTER("Hamster"),
    HARPY("Harpy", "Harpies"),
    HEDGEHOG("Hedgehog"),
    HELLION("Hellion"),
    HERO("Hero", "Heroes"),
    HIPPO("Hippo"),
    HIPPOGRIFF("Hippogriff"),
    HOMARID("Homarid"),
    HOMUNCULUS("Homunculus", "Homunculuses"),
    HORROR("Horror"),
    HORSE("Horse"),
    HUMAN("Human"),
    HYDRA("Hydra"),
    HYENA("Hyena"),
    ILLUSION("Illusion"),
    IMP("Imp"),
    INCARNATION("Incarnation"),
    INKLING("Inkling"),
    INQUISITOR("Inquisitor"),
    INSECT("Insect"),
    JACKAL("Jackal"),
    JELLYFISH("Jellyfish", "Jellyfish"),
    JUGGERNAUT("Juggernaut"),
    KANGAROO("Kangaroo"),
    KAVU("Kavu", "Kavu"),
    KIRIN("Kirin"),
    KITHKIN("Kithkin", "Kithkin"),
    KNIGHT("Knight"),
    KOBOLD("Kobold"),
    KOR("Kor", "Kor"),
    KRAKEN("Kraken"),
    LLAMA("Llama"),
    LAMIA("Lamia"),
    LAMMASU("Lammasu"),
    LEECH("Leech", "Leeches"),
    LEMUR("Lemur"),
    LEVIATHAN("Leviathan"),
    LHURGOYF("Lhurgoyf"),
    LICID("Licid"),
    LIZARD("Lizard"),
    LOBSTER("Lobster"),
    MANTICORE("Manticore"),
    MASTICORE("Masticore"),
    MERCENARY("Mercenary", "Mercenaries"),
    MERFOLK("Merfolk", "Merfolk"),
    METATHRAN("Metathran", "Metathran"),
    MINION("Minion"),
    MINOTAUR("Minotaur"),
    MITE("Mite"),
    MOLE("Mole"),
    MONGER("Monger"),
    MONGOOSE("Mongoose"),
    MONK("Monk"),
    MONKEY("Monkey"),
    MOOGLE("Moogle"),
    MOONFOLK("Moonfolk", "Moonfolk"),
    MOUNT("Mount"),
    MOUSE("Mouse", "Mice"),
    MUTANT("Mutant"),
    MYR("Myr", "Myr"),
    MYSTIC("Mystic"),
    NAUTILUS("Nautilus", "Nautiluses"),
    NECRON("Necron"),
    NEPHILIM("Nephilim", "Nephilim"),
    NIGHTMARE("Nightmare"),
    NIGHTSTALKER("Nightstalker"),
    NINJA("Ninja"),
    NOBLE("Noble"),
    NOGGLE("Noggle"),
    NOMAD("Nomad"),
    NYMPH("Nymph"),
    OCTOPUS("Octopus", "Octopuses"),
    OGRE("Ogre"),
    OOZE("Ooze"),
    ORB("Orb"),
    ORC("Orc"),
    ORGG("Orgg"),
    OTTER("Otter"),
    OUPHE("Ouphe"),
    OX("Ox", "Oxen"),
    OYSTER("Oyster"),
    PANGOLIN("Pangolin"),
    PEASANT("Peasant"),
    PEGASUS("Pegasus", "Pegasuses"),
    PENTAVITE("Pentavite"),
    PERFORMER("Performer"),
    PEST("Pest"),
    PHELDDAGRIF("Phelddagrif"),
    PHOENIX("Phoenix", "Phoenixes"),
    PHYREXIAN("Phyrexian"),
    PILOT("Pilot"),
    PINCHER("Pincher"),
    PIRATE("Pirate"),
    PLANT("Plant"),
    PLATYPUS("Platypus", "Platypuses"),
    PORCUPINE("Porcupine"),
    POSSUM("Possum"),
    PRAETOR("Praetor"),
    PRIMARCH("Primarch"),
    PRISM("Prism"),
    PROCESSOR("Processor"),
    QU("Qu", "Qu"),
    RABBIT("Rabbit"),
    RACCOON("Raccoon"),
    RANGER("Ranger"),
    RAT("Rat"),
    REBEL("Rebel"),
    REFLECTION("Reflection"),
    RHINO("Rhino"),
    RIGGER("Rigger"),
    ROBOT("Robot"),
    ROGUE("Rogue"),
    SABLE("Sable"),
    SALAMANDER("Salamander"),
    SAMURAI("Samurai", "Samurai"),
    SAND("Sand"),
    SAPROLING("Saproling"),
    SATYR("Satyr"),
    SCARECROW("Scarecrow"),
    SCIENTIST("Scientist"),
    SCION("Scion"),
    SCORPION("Scorpion"),
    SCOUT("Scout"),
    SCULPTURE("Sculpture"),
    SEAL("Seal"),
    SERF("Serf"),
    SERPENT("Serpent"),
    SERVO("Servo"),
    SHADE("Shade"),
    SHAMAN("Shaman"),
    SHAPESHIFTER("Shapeshifter"),
    SHARK("Shark"),
    SHEEP("Sheep", "Sheep"),
    SIREN("Siren"),
    SKELETON("Skeleton"),
    SKUNK("Skunk"),
    SLITH("Slith"),
    SLIVER("Sliver"),
    SLOTH("Sloth"),
    SLUG("Slug"),
    SNAIL("Snail"),
    SNAKE("Snake"),
    SOLDIER("Soldier"),
    SOLTARI("Soltari", "Soltari"),
    SORCERER("Sorcerer"),
    SPAWN("Spawn", "Spawn"),
    SPECTER("Specter"),
    SPELLSHAPER("Spellshaper"),
    SPHINX("Sphinx", "Sphinxes"),
    SPIDER("Spider"),
    SPIKE("Spike"),
    SPIRIT("Spirit"),
    SPLINTER("Splinter"),
    SPONGE("Sponge"),
    SQUID("Squid"),
    SQUIRREL("Squirrel"),
    STARFISH("Starfish", "Starfish"),
    SURRAKAR("Surrakar", "Surrakar"),
    SURVIVOR("Survivor"),
    SYMBIOTE("Symbiote"),
    SYNTH("Synth"),
    TENTACLE("Tentacle"),
    TETRAVITE("Tetravite"),
    THALAKOS("Thalakos", "Thalakos"),
    THOPTER("Thopter"),
    THRULL("Thrull"),
    TIEFLING("Tiefling"),
    TIME_LORD("Time Lord"),
    TOY("Toy"),
    TREEFOLK("Treefolk", "Treefolk"),
    TRILOBITE("Trilobite"),
    TRISKELAVITE("Triskelavite"),
    TROLL("Troll"),
    TURTLE("Turtle"),
    TYRANID("Tyranid"),
    UNICORN("Unicorn"),
    UTROM("Utrom"),
    VAMPIRE("Vampire"),
    VARMINT("Varmint"),
    VEDALKEN("Vedalken", "Vedalken"),
    VILLAIN("Villain"),
    VOLVER("Volver"),
    WALL("Wall"),
    WALRUS("Walrus", "Walruses"),
    WARLOCK("Warlock"),
    WARRIOR("Warrior"),
    WEASEL("Weasel"),
    WEIRD("Weird"),
    WEREWOLF("Werewolf", "Werewolves"),
    WHALE("Whale"),
    WIZARD("Wizard"),
    WOLF("Wolf", "Wolves"),
    WOLVERINE("Wolverine"),
    WOMBAT("Wombat"),
    WORM("Worm"),
    WRAITH("Wraith"),
    WURM("Wurm"),
    YETI("Yeti"),
    ZOMBIE("Zombie"),
    ZUBERA("Zubera", "Zubera");

    private final String text;
    private final List<String> texts;

    CreatureType(String text) {
        this(text, text + "s");
    }

    CreatureType(String text, String plural) {
        this.text = text;
        this.texts = plural.equals(text) ? List.of(text) : List.of(text, plural);
    }

    public String text() {
        return text;
    }

    @Override
    public List<String> texts() {
        return texts;
    }

    @Override
    public String toString() {
        return text;
    }
}
