package be.imgn.mtg.engine.oracle2.domain.selector;

import static be.imgn.mtg.engine.oracle2.domain.selector.ObjectPropertySelector.Anything.ANYTHING;
import static java.util.Objects.requireNonNull;

/// Game-object class (CR 109.1) — the engine's dispatch layer for
/// "what kind of object" the selection is about: a `Permanent` /
/// `Token` (battlefield), a `Spell` / `Ability` / `Copy` (stack), or
/// a `Card` / `Emblem` (everywhere else / command zone). Distinct
/// from card-type characteristics (creature, artifact, …) which live
/// as [CharacteristicSelector] arms inside the `where` slot below.
///
/// Each leaf record carries an [ObjectPropertySelector] `where` slot
/// — the predicate constraining which instance of that object class
/// is selected. The default no-arg constructor leaves the predicate
/// as [ObjectPropertySelector.Anything#ANYTHING]; the [#withWhere]
/// wither attaches a non-default predicate. Each leaf also implements
/// the appropriate per-zone `Contents` interface
/// ([ZoneSelector.Battlefield.Contents], [ZoneSelector.Stack.Contents],
/// [ZoneSelector.CommandZone.Contents]) so the type system enforces
/// the zone↔class coupling.
///
/// `Copy` lives only on the Stack (CR 707.10): a copy of a permanent
/// spell becomes a `Token` as it resolves (CR 111.13, 608.3f, 707.10f).
/// `Emblem` lives only in the Command zone (CR 114, 408.2c).
public sealed interface ObjectTypeSelector
        permits ObjectTypeSelector.Permanent,
                ObjectTypeSelector.Token,
                ObjectTypeSelector.Spell,
                ObjectTypeSelector.Ability,
                ObjectTypeSelector.Copy,
                ObjectTypeSelector.Card,
                ObjectTypeSelector.Emblem {

    /// The predicate constraining which instance of this object class
    /// is selected. Generated by the record components on each arm.
    ObjectPropertySelector where();

    /// Returns a copy of this selector with the `where` predicate
    /// replaced by `where`. Polymorphic across all 7 arms.
    ObjectTypeSelector withWhere(ObjectPropertySelector where);

    record Permanent(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.Battlefield.Contents {
        public Permanent {
            requireNonNull(where);
        }

        public Permanent() {
            this(ANYTHING);
        }

        @Override
        public Permanent withWhere(ObjectPropertySelector where) {
            return new Permanent(where);
        }
    }

    record Token(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.Battlefield.Contents {
        public Token {
            requireNonNull(where);
        }

        public Token() {
            this(ANYTHING);
        }

        @Override
        public Token withWhere(ObjectPropertySelector where) {
            return new Token(where);
        }
    }

    record Spell(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.Stack.Contents {
        public Spell {
            requireNonNull(where);
        }

        public Spell() {
            this(ANYTHING);
        }

        @Override
        public Spell withWhere(ObjectPropertySelector where) {
            return new Spell(where);
        }
    }

    record Ability(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.Stack.Contents {
        public Ability {
            requireNonNull(where);
        }

        public Ability() {
            this(ANYTHING);
        }

        @Override
        public Ability withWhere(ObjectPropertySelector where) {
            return new Ability(where);
        }
    }

    /// Copy of a spell or ability on the Stack ({@mtg.rule 707.10}).
    /// Copies of permanent spells become Tokens as they resolve
    /// ({@mtg.rule 111.13}, {@mtg.rule 608.3f}, {@mtg.rule 707.10f}) —
    /// they never reach the Battlefield as a Copy.
    record Copy(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.Stack.Contents {
        public Copy {
            requireNonNull(where);
        }

        public Copy() {
            this(ANYTHING);
        }

        @Override
        public Copy withWhere(ObjectPropertySelector where) {
            return new Copy(where);
        }
    }

    record Card(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.CommandZone.Contents {
        public Card {
            requireNonNull(where);
        }

        public Card() {
            this(ANYTHING);
        }

        @Override
        public Card withWhere(ObjectPropertySelector where) {
            return new Card(where);
        }
    }

    /// Emblem ({@mtg.rule 114}). Lives exclusively in the Command zone
    /// ({@mtg.rule 408.2c}).
    record Emblem(ObjectPropertySelector where) implements ObjectTypeSelector, ZoneSelector.CommandZone.Contents {
        public Emblem {
            requireNonNull(where);
        }

        public Emblem() {
            this(ANYTHING);
        }

        @Override
        public Emblem withWhere(ObjectPropertySelector where) {
            return new Emblem(where);
        }
    }
}
